/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { execSync } = require('child_process')

function termuxSetText(value) {
  try {
    execSync('termux-clipboard-set', {
      input: value,
      stdio: ['pipe', 'pipe', 'pipe'],
    })
  } catch {
    throw new Error('Failed to set clipboard')
  }
}

function termuxGetText() {
  try {
    return execSync('termux-clipboard-get', {
      encoding: 'utf8',
    })
  } catch {
    return ''
  }
}

function termuxHasText() {
  try {
    const text = execSync('termux-clipboard-get', {
      encoding: 'utf8',
    })
    return text.length > 0
  } catch {
    return false
  }
}

module.exports.availableFormats = () => []
module.exports.getText = termuxGetText
module.exports.setText = termuxSetText
module.exports.hasText = termuxHasText
module.exports.getImageBinary = () => null
module.exports.getImageBase64 = () => ''
module.exports.setImageBinary = () => {}
module.exports.setImageBase64 = () => {}
module.exports.hasImage = () => false
module.exports.getHtml = () => ''
module.exports.setHtml = () => {}
module.exports.hasHtml = () => false
module.exports.getRtf = () => ''
module.exports.setRtf = () => {}
module.exports.hasRtf = () => false
module.exports.clear = () => {}
module.exports.watch = () => {}
module.exports.callThreadsafeFunction = () => {}
